# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nodemcu.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 352)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_1 = QtWidgets.QFrame(self.centralwidget)
        self.frame_1.setGeometry(QtCore.QRect(10, 10, 71, 241))
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.heading_1 = QtWidgets.QLabel(self.frame_1)
        self.heading_1.setGeometry(QtCore.QRect(10, 10, 51, 17))
        self.heading_1.setObjectName("heading_1")
        self.servo_slider_1 = QtWidgets.QSlider(self.frame_1)
        self.servo_slider_1.setGeometry(QtCore.QRect(20, 30, 29, 160))
        self.servo_slider_1.setAutoFillBackground(True)
        self.servo_slider_1.setMaximum(180)
        self.servo_slider_1.setProperty("value", 90)
        self.servo_slider_1.setSliderPosition(90)
        self.servo_slider_1.setOrientation(QtCore.Qt.Vertical)
        self.servo_slider_1.setInvertedAppearance(False)
        self.servo_slider_1.setInvertedControls(False)
        self.servo_slider_1.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.servo_slider_1.setObjectName("servo_slider_1")
        self.pin_st_1 = QtWidgets.QLabel(self.frame_1)
        self.pin_st_1.setGeometry(QtCore.QRect(10, 190, 51, 17))
        self.pin_st_1.setObjectName("pin_st_1")
        self.servo_spinBox_1 = QtWidgets.QSpinBox(self.frame_1)
        self.servo_spinBox_1.setGeometry(QtCore.QRect(9, 210, 54, 27))
        self.servo_spinBox_1.setMaximum(180)
        self.servo_spinBox_1.setProperty("value", 90)
        self.servo_spinBox_1.setObjectName("servo_spinBox_1")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(90, 10, 71, 241))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.heading_2 = QtWidgets.QLabel(self.frame_2)
        self.heading_2.setGeometry(QtCore.QRect(10, 10, 51, 17))
        self.heading_2.setObjectName("heading_2")
        self.servo_slider_2 = QtWidgets.QSlider(self.frame_2)
        self.servo_slider_2.setGeometry(QtCore.QRect(20, 30, 29, 160))
        self.servo_slider_2.setAutoFillBackground(True)
        self.servo_slider_2.setMaximum(180)
        self.servo_slider_2.setProperty("value", 90)
        self.servo_slider_2.setSliderPosition(90)
        self.servo_slider_2.setOrientation(QtCore.Qt.Vertical)
        self.servo_slider_2.setInvertedAppearance(False)
        self.servo_slider_2.setInvertedControls(False)
        self.servo_slider_2.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.servo_slider_2.setObjectName("servo_slider_2")
        self.pin_st_2 = QtWidgets.QLabel(self.frame_2)
        self.pin_st_2.setGeometry(QtCore.QRect(10, 190, 51, 17))
        self.pin_st_2.setObjectName("pin_st_2")
        self.servo_spinBox_2 = QtWidgets.QSpinBox(self.frame_2)
        self.servo_spinBox_2.setGeometry(QtCore.QRect(9, 210, 54, 27))
        self.servo_spinBox_2.setMaximum(180)
        self.servo_spinBox_2.setProperty("value", 90)
        self.servo_spinBox_2.setObjectName("servo_spinBox_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(170, 10, 71, 241))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.heading_3 = QtWidgets.QLabel(self.frame_3)
        self.heading_3.setGeometry(QtCore.QRect(10, 10, 51, 17))
        self.heading_3.setObjectName("heading_3")
        self.servo_slider_3 = QtWidgets.QSlider(self.frame_3)
        self.servo_slider_3.setGeometry(QtCore.QRect(20, 30, 29, 160))
        self.servo_slider_3.setAutoFillBackground(True)
        self.servo_slider_3.setMaximum(180)
        self.servo_slider_3.setProperty("value", 90)
        self.servo_slider_3.setSliderPosition(90)
        self.servo_slider_3.setOrientation(QtCore.Qt.Vertical)
        self.servo_slider_3.setInvertedAppearance(False)
        self.servo_slider_3.setInvertedControls(False)
        self.servo_slider_3.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.servo_slider_3.setObjectName("servo_slider_3")
        self.pin_st_3 = QtWidgets.QLabel(self.frame_3)
        self.pin_st_3.setGeometry(QtCore.QRect(10, 190, 51, 17))
        self.pin_st_3.setObjectName("pin_st_3")
        self.servo_spinBox_3 = QtWidgets.QSpinBox(self.frame_3)
        self.servo_spinBox_3.setGeometry(QtCore.QRect(9, 210, 54, 27))
        self.servo_spinBox_3.setMaximum(180)
        self.servo_spinBox_3.setProperty("value", 90)
        self.servo_spinBox_3.setObjectName("servo_spinBox_3")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(250, 10, 71, 241))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.heading_4 = QtWidgets.QLabel(self.frame_4)
        self.heading_4.setGeometry(QtCore.QRect(10, 10, 51, 17))
        self.heading_4.setObjectName("heading_4")
        self.servo_slider_4 = QtWidgets.QSlider(self.frame_4)
        self.servo_slider_4.setGeometry(QtCore.QRect(20, 30, 29, 160))
        self.servo_slider_4.setAutoFillBackground(True)
        self.servo_slider_4.setMaximum(180)
        self.servo_slider_4.setProperty("value", 90)
        self.servo_slider_4.setSliderPosition(90)
        self.servo_slider_4.setOrientation(QtCore.Qt.Vertical)
        self.servo_slider_4.setInvertedAppearance(False)
        self.servo_slider_4.setInvertedControls(False)
        self.servo_slider_4.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.servo_slider_4.setObjectName("servo_slider_4")
        self.pin_st_4 = QtWidgets.QLabel(self.frame_4)
        self.pin_st_4.setGeometry(QtCore.QRect(10, 190, 51, 17))
        self.pin_st_4.setObjectName("pin_st_4")
        self.servo_spinBox_4 = QtWidgets.QSpinBox(self.frame_4)
        self.servo_spinBox_4.setGeometry(QtCore.QRect(9, 210, 54, 27))
        self.servo_spinBox_4.setMaximum(180)
        self.servo_spinBox_4.setProperty("value", 90)
        self.servo_spinBox_4.setObjectName("servo_spinBox_4")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(330, 10, 71, 241))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.heading_5 = QtWidgets.QLabel(self.frame_5)
        self.heading_5.setGeometry(QtCore.QRect(10, 10, 51, 17))
        self.heading_5.setObjectName("heading_5")
        self.servo_slider_5 = QtWidgets.QSlider(self.frame_5)
        self.servo_slider_5.setGeometry(QtCore.QRect(20, 30, 29, 160))
        self.servo_slider_5.setAutoFillBackground(True)
        self.servo_slider_5.setMaximum(180)
        self.servo_slider_5.setProperty("value", 90)
        self.servo_slider_5.setSliderPosition(90)
        self.servo_slider_5.setOrientation(QtCore.Qt.Vertical)
        self.servo_slider_5.setInvertedAppearance(False)
        self.servo_slider_5.setInvertedControls(False)
        self.servo_slider_5.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.servo_slider_5.setObjectName("servo_slider_5")
        self.pin_st_5 = QtWidgets.QLabel(self.frame_5)
        self.pin_st_5.setGeometry(QtCore.QRect(10, 190, 51, 17))
        self.pin_st_5.setObjectName("pin_st_5")
        self.servo_spinBox_5 = QtWidgets.QSpinBox(self.frame_5)
        self.servo_spinBox_5.setGeometry(QtCore.QRect(9, 210, 54, 27))
        self.servo_spinBox_5.setMaximum(180)
        self.servo_spinBox_5.setProperty("value", 90)
        self.servo_spinBox_5.setObjectName("servo_spinBox_5")

        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(410, 10, 71, 241))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.heading_6 = QtWidgets.QLabel(self.frame_6)
        self.heading_6.setGeometry(QtCore.QRect(10, 10, 51, 17))
        self.heading_6.setObjectName("heading_6")
        self.servo_slider_6 = QtWidgets.QSlider(self.frame_6)
        self.servo_slider_6.setGeometry(QtCore.QRect(20, 30, 29, 160))
        self.servo_slider_6.setAutoFillBackground(True)
        self.servo_slider_6.setMaximum(180)
        self.servo_slider_6.setProperty("value", 90)
        self.servo_slider_6.setSliderPosition(90)
        self.servo_slider_6.setOrientation(QtCore.Qt.Vertical)
        self.servo_slider_6.setInvertedAppearance(False)
        self.servo_slider_6.setInvertedControls(False)
        self.servo_slider_6.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.servo_slider_6.setObjectName("servo_slider_6")
        self.pin_st_6 = QtWidgets.QLabel(self.frame_6)
        self.pin_st_6.setGeometry(QtCore.QRect(10, 190, 51, 17))
        self.pin_st_6.setObjectName("pin_st_6")
        self.servo_spinBox_6 = QtWidgets.QSpinBox(self.frame_6)
        self.servo_spinBox_6.setGeometry(QtCore.QRect(9, 210, 54, 27))
        self.servo_spinBox_6.setMaximum(180)
        self.servo_spinBox_6.setProperty("value", 90)
        self.servo_spinBox_6.setObjectName("servo_spinBox_6")
        
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(490, 10, 71, 241))
        self.frame_7.setMouseTracking(False)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.heading_7 = QtWidgets.QLabel(self.frame_7)
        self.heading_7.setGeometry(QtCore.QRect(10, 10, 51, 17))
        self.heading_7.setObjectName("heading_7")
        self.servo_slider_7 = QtWidgets.QSlider(self.frame_7)
        self.servo_slider_7.setGeometry(QtCore.QRect(20, 30, 29, 160))
        self.servo_slider_7.setAutoFillBackground(True)
        self.servo_slider_7.setMaximum(180)
        self.servo_slider_7.setProperty("value", 90)
        self.servo_slider_7.setSliderPosition(90)
        self.servo_slider_7.setOrientation(QtCore.Qt.Vertical)
        self.servo_slider_7.setInvertedAppearance(False)
        self.servo_slider_7.setInvertedControls(False)
        self.servo_slider_7.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.servo_slider_7.setObjectName("servo_slider_7")
        self.pin_st_7 = QtWidgets.QLabel(self.frame_7)
        self.pin_st_7.setGeometry(QtCore.QRect(10, 190, 51, 17))
        self.pin_st_7.setObjectName("pin_st_7")
        self.servo_spinBox_7 = QtWidgets.QSpinBox(self.frame_7)
        self.servo_spinBox_7.setGeometry(QtCore.QRect(9, 210, 54, 27))
        self.servo_spinBox_7.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.servo_spinBox_7.setMaximum(180)
        self.servo_spinBox_7.setProperty("value", 90)
        self.servo_spinBox_7.setObjectName("servo_spinBox_7")

        self.frame_8 = QtWidgets.QFrame(self.centralwidget)
        self.frame_8.setGeometry(QtCore.QRect(570, 10, 71, 241))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.heading_8 = QtWidgets.QLabel(self.frame_8)
        self.heading_8.setGeometry(QtCore.QRect(10, 10, 51, 17))
        self.heading_8.setObjectName("heading_8")
        self.servo_slider_8 = QtWidgets.QSlider(self.frame_8)
        self.servo_slider_8.setGeometry(QtCore.QRect(20, 30, 29, 160))
        self.servo_slider_8.setAutoFillBackground(True)
        self.servo_slider_8.setMaximum(180)
        self.servo_slider_8.setProperty("value", 90)
        self.servo_slider_8.setSliderPosition(90)
        self.servo_slider_8.setOrientation(QtCore.Qt.Vertical)
        self.servo_slider_8.setInvertedAppearance(False)
        self.servo_slider_8.setInvertedControls(False)
        self.servo_slider_8.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.servo_slider_8.setObjectName("servo_slider_8")
        self.pin_st_8 = QtWidgets.QLabel(self.frame_8)
        self.pin_st_8.setGeometry(QtCore.QRect(10, 190, 51, 17))
        self.pin_st_8.setObjectName("pin_st_8")
        self.servo_spinBox_8 = QtWidgets.QSpinBox(self.frame_8)
        self.servo_spinBox_8.setGeometry(QtCore.QRect(9, 210, 54, 27))
        self.servo_spinBox_8.setMaximum(180)
        self.servo_spinBox_8.setProperty("value", 90)
        self.servo_spinBox_8.setObjectName("servo_spinBox_8")
        self.frame_9 = QtWidgets.QFrame(self.centralwidget)
        self.frame_9.setGeometry(QtCore.QRect(650, 10, 71, 241))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.heading_9 = QtWidgets.QLabel(self.frame_9)
        self.heading_9.setGeometry(QtCore.QRect(10, 10, 51, 17))
        self.heading_9.setObjectName("heading_9")
        self.servo_slider_9 = QtWidgets.QSlider(self.frame_9)
        self.servo_slider_9.setGeometry(QtCore.QRect(20, 30, 29, 160))
        self.servo_slider_9.setAutoFillBackground(True)
        self.servo_slider_9.setMaximum(180)
        self.servo_slider_9.setProperty("value", 90)
        self.servo_slider_9.setSliderPosition(90)
        self.servo_slider_9.setOrientation(QtCore.Qt.Vertical)
        self.servo_slider_9.setInvertedAppearance(False)
        self.servo_slider_9.setInvertedControls(False)
        self.servo_slider_9.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.servo_slider_9.setObjectName("servo_slider_9")
        self.pin_st_9 = QtWidgets.QLabel(self.frame_9)
        self.pin_st_9.setGeometry(QtCore.QRect(10, 190, 51, 17))
        self.pin_st_9.setObjectName("pin_st_9")
        self.servo_spinBox_9 = QtWidgets.QSpinBox(self.frame_9)
        self.servo_spinBox_9.setGeometry(QtCore.QRect(9, 210, 54, 27))
        self.servo_spinBox_9.setMaximum(180)
        self.servo_spinBox_9.setProperty("value", 90)
        self.servo_spinBox_9.setObjectName("servo_spinBox_9")
        self.frame_10 = QtWidgets.QFrame(self.centralwidget)
        self.frame_10.setGeometry(QtCore.QRect(730, 10, 71, 241))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.heading_10 = QtWidgets.QLabel(self.frame_10)
        self.heading_10.setGeometry(QtCore.QRect(7, 11, 60, 17))
        self.heading_10.setObjectName("heading_10")
        self.servo_slider_10 = QtWidgets.QSlider(self.frame_10)
        self.servo_slider_10.setGeometry(QtCore.QRect(20, 30, 29, 160))
        self.servo_slider_10.setAutoFillBackground(True)
        self.servo_slider_10.setMaximum(180)
        self.servo_slider_10.setProperty("value", 90)
        self.servo_slider_10.setSliderPosition(90)
        self.servo_slider_10.setOrientation(QtCore.Qt.Vertical)
        self.servo_slider_10.setInvertedAppearance(False)
        self.servo_slider_10.setInvertedControls(False)
        self.servo_slider_10.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.servo_slider_10.setObjectName("servo_slider_10")
        self.pin_st_10 = QtWidgets.QLabel(self.frame_10)
        self.pin_st_10.setGeometry(QtCore.QRect(8, 190, 54, 17))
        self.pin_st_10.setObjectName("pin_st_10")
        self.servo_spinBox_10 = QtWidgets.QSpinBox(self.frame_10)
        self.servo_spinBox_10.setGeometry(QtCore.QRect(9, 210, 54, 27))
        self.servo_spinBox_10.setMaximum(180)
        self.servo_spinBox_10.setProperty("value", 90)
        self.servo_spinBox_10.setObjectName("servo_spinBox_10")
        
        self.frame_11 = QtWidgets.QFrame(self.centralwidget)
        self.frame_11.setGeometry(QtCore.QRect(10, 260, 551, 41))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.ser_label = QtWidgets.QLabel(self.frame_11)
        self.ser_label.setGeometry(QtCore.QRect(30, 10, 80, 20))
        self.ser_label.setObjectName("ser_label")
        self.ser_checkBox = QtWidgets.QCheckBox(self.frame_11)
        self.ser_checkBox.setGeometry(QtCore.QRect(10, 10, 21, 22))
        self.ser_checkBox.setObjectName("ser_checkBox")
        self.cnn_status = QtWidgets.QLabel(self.frame_11)
        self.cnn_status.setGeometry(QtCore.QRect(430, 10, 111, 20))
        self.cnn_status.setObjectName("cnn_status")
        self.spd_comboBox = QtWidgets.QComboBox(self.frame_11)
        self.spd_comboBox.setGeometry(QtCore.QRect(310, 7, 111, 27))
        self.spd_comboBox.setObjectName("spd_comboBox")
        self.ser_comboBox = QtWidgets.QComboBox(self.frame_11)
        self.ser_comboBox.setGeometry(QtCore.QRect(110, 7, 111, 27))
        self.ser_comboBox.setObjectName("ser_comboBox")
        self.baud_label = QtWidgets.QLabel(self.frame_11)
        self.baud_label.setGeometry(QtCore.QRect(230, 10, 71, 17))
        self.baud_label.setObjectName("baud_label")
        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setGeometry(QtCore.QRect(650, 270, 151, 27))
        self.btn.setObjectName("btn")
        self.frame_11.raise_()
        self.frame_1.raise_()
        self.frame_2.raise_()
        self.frame_4.raise_()
        self.frame_3.raise_()
        self.frame_6.raise_()
        self.frame_5.raise_()
        self.frame_8.raise_()
        self.frame_9.raise_()
        self.frame_10.raise_()
        self.frame_7.raise_()
        self.btn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 25))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExit_ = QtWidgets.QAction(MainWindow)
        self.actionExit_.setObjectName("actionExit_")
        self.actionHow_to = QtWidgets.QAction(MainWindow)
        self.actionHow_to.setObjectName("actionHow_to")
        self.actionFeedback = QtWidgets.QAction(MainWindow)
        self.actionFeedback.setObjectName("actionFeedback")
        self.actionAbout_developer = QtWidgets.QAction(MainWindow)
        self.actionAbout_developer.setObjectName("actionAbout_developer")
        self.menuMenu.addAction(self.actionExit_)
        self.menuAbout.addAction(self.actionHow_to)
        self.menuAbout.addAction(self.actionFeedback)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionAbout_developer)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NodeMCU Servo Controller"))
        self.heading_1.setText(_translate("MainWindow", "Servo 1"))
        self.pin_st_1.setText(_translate("MainWindow", "Pin D1"))
        self.heading_2.setText(_translate("MainWindow", "Servo 2"))
        self.pin_st_2.setText(_translate("MainWindow", "Pin D2"))
        self.heading_4.setText(_translate("MainWindow", "Servo 4"))
        self.pin_st_4.setText(_translate("MainWindow", "Pin D4"))
        self.heading_3.setText(_translate("MainWindow", "Servo 3"))
        self.pin_st_3.setText(_translate("MainWindow", "Pin D3"))
        self.heading_6.setText(_translate("MainWindow", "Servo 6"))
        self.pin_st_6.setText(_translate("MainWindow", "Pin D6"))
        self.heading_5.setText(_translate("MainWindow", "Servo 5"))
        self.pin_st_5.setText(_translate("MainWindow", "Pin D5"))
        self.heading_8.setText(_translate("MainWindow", "Servo 8"))
        self.pin_st_8.setText(_translate("MainWindow", "Pin D8"))
        self.heading_9.setText(_translate("MainWindow", "Servo 9"))
        self.pin_st_9.setText(_translate("MainWindow", "Pin D9"))
        self.heading_10.setText(_translate("MainWindow", "Servo 10"))
        self.pin_st_10.setText(_translate("MainWindow", "Pin D10"))
        self.heading_7.setText(_translate("MainWindow", "Servo 7"))
        self.pin_st_7.setText(_translate("MainWindow", "Pin D7"))
        self.ser_label.setText(_translate("MainWindow", "SerialPort :"))
        self.ser_checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.cnn_status.setText(_translate("MainWindow", "Not Connected"))
        self.baud_label.setText(_translate("MainWindow", "Baud Rate"))
        self.btn.setText(_translate("MainWindow", "Connect"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit_.setText(_translate("MainWindow", "Exit"))
        self.actionHow_to.setText(_translate("MainWindow", "How to"))
        self.actionFeedback.setText(_translate("MainWindow", "Feedback"))
        self.actionAbout_developer.setText(_translate("MainWindow", "About developer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

